# Generated by Django 2.2 on 2021-05-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
